### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Ryze-T** [Accenture/VulFi#2]
![image](https://user-images.githubusercontent.com/76553352/157840166-7a57488f-0e8c-47d8-adc7-e5b0c00db9bd.png)
What i can do ?

**Comment by Martyx00** [comment]
Hello, thanks for reporting this. The problem seems to be that Python version on your machine is <3.8.
The `:=` operator was I believe introduced in version 3.8 and allows assignments in expressions (something I was happy to find out). If I am not mistaken, IDA version 7.5 should support Python 3.9 so updating your version of Python should address the issue. In case it does not, let me know, I will change the code to not use the code construct that causes the problem :)

**Comment by nobodyisnobody** [comment]
You should just rewrite the comparaison for backward compatibility:

```
answer = ida_kernwin.ask_buttons("Load Existing","Scan Again","Cancel",1,f"Previous scan results found.")
if vulfi_data and (answer == 1):

```

**Comment by Martyx00** [comment]
Fixed with https://github.com/Accenture/VulFi/commit/9507fdddc2d3bb30b506356692e988851aac8876. Although you should update your Python :)
