### ISSUE TITLE
Add the possibility of exporting the VulFi results as CSV or JSON.

### ISSUE THREAD

**Issue by Martyx00** [Accenture/VulFi#7]
Add export for JSON and CSV files.

Note: Add import feature as well.

**Comment by Martyx00** [comment]
https://github.com/Accenture/VulFi/commit/3b25268ac5eb8049873bfa4218a3f717a3add38a

**Comment by Martyx00** [comment]
Import and Export: https://github.com/Accenture/VulFi/commit/8e675218f6878710ee7d12d6b94036fc12a515cd

**Comment by VoidSec** [comment]
The "export results" functionality has 2 bugs:

1. Once the "export results" functionality has been used and the file is successfully saved, the same "export dialog" (shown in the image below) continues popping out. Cancel, close or save buttons do not dismiss it.
2. Export dialog reads as "Custom VulFi Rule" instead of "Export Vulfi Results"
![immagine](https://user-images.githubusercontent.com/5717603/201683134-0cdd7a54-3447-444b-8546-b1ee25148736.png)

**Comment by Martyx00** [comment]
Thanks for reporting, fixed with https://github.com/Accenture/VulFi/commit/649ac144e3a34f7f47f084faa333e823dee0a079
